# Build and test configuration for travis-ci.com.

language: c
script: make clean check
matrix:
  include:
    - os: osx
      osx_image: xcode11.2
      compiler: clang
    - os: linux
      compiler: clang
    - os: linux
      compiler: gcc

