name: Unit tests

on: [push]
    
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v2
    - name: make test    # unit tests
      run: make test
    - name: make check   # unit and compatibility tests
      run: make check
